from account import *
import random

def create_accounts():
    """
    Reads the data file and sets up all of the existing accounts an object under the class 'accounts'


    Parameters
    ----------
    None

    Returns
    -------
    None

    """
    # opens text file
    file = open(file_path, 'r')
    data = file.readlines()

    # creates accounts
    i = int(data[0])
    answered = ['0', '0', '0', '0', '0']
    attempts = ['0', '0', '0', '0', '0']
    for x in range(0, 5):
        answered[x] = data[i + 2 + x]
        attempts[x] = data[i + 7 + x]

    accounts.append(Account(i, data[i+1], answered, attempts))


def set_type():
    """
    Sets the type of problem between the 4 arithmetic operators

    Changes the value of the string 'problem_type' to an item in the list 'problem_types'

	Parameters
	----------
	None

	Returns
    -------
	str
	    Returns the input if it is a valid problem type

    """

    setp = input("\nSelect a type of problem: addition, subtraction, multiplication, division\n")
    while setp not in problem_types:
        print("\nThat is not an option!")
        setp = input("Select a type of problem: addition, subtraction, multiplication, division\n")
    return setp


def set_dif():
    """
    Sets the difficulty of the problems

    Changes the value of the string 'difficulty' to an item in the list 'difficulties'

	Parameters
	----------
	None

	Returns
    -------
	str
	    Returns the input if it is a valid difficulty

    """

    setd = input("\nSelect a difficulty: easy, medium, hard\n")
    while setd not in difficulties:
        print("\nThat is not an option!")
        setd = input("Select a difficulty: easy, medium, hard\n")
    return setd


def problem(question, correct_answer, type):
    """
    Asks a problem and checks for the correct answer of the problem

	Parameters
	----------
	question : str
	    The problem that is to be asked based on the type of problem generated by the functions: 'addition()',
	    'subtraction()', 'multiplication()', and 'division()'
	correct_answer : float
	    The correct answer of the problem
	type : int
	    The type of problem as the index of 'problem_types'

	Returns
    -------
    None

	Raises
	------
	ValueError
	    If the value of increase is not a float and it is trying to convert it into a float

    """

    # Asks the inputted question
    answer = input(question)

    # Checks for difficulty or problem type change
    navigate(answer)

    # List of previous answers for question
    answers = [answer]
    while float(answer) != correct_answer:
        # 1 answer
        if len(answers) == 1:
            print("\n" + answers[0] + " is incorrect!")

        # 2 or more answers
        else:
            # lists previous incorrect answers
            print("\n")
            for i in range(len(answers)):
                if i == len(answers) - 1:
                    print("and " + answers[i], end='')
                else:
                    print(answers[i] + ", ", end='')
            print(" are incorrect!")

        print("Try again.")
        # +1 on attempted problems and total attempts for this account
        accounts[active].addAttempts(type)

        # Next inputted answer
        answer = input(question)

        # Checks for difficulty or problem type change
        navigate(answer)

        # Adds answer to list
        answers.append(answer)

    # Random praise upon getting the correct answer
    print(random.choice(praises))

    # +1 on solved problems and total answered for this account and attempts/total attempts
    accounts[active].addAnswered(type)
    accounts[active].addAttempts(type)

def addition(dif):
    """
    Generates an addition problem based on the difficulty and generates 2 random integers,
    then asks the problem by calling the function 'problem()'

    Parameters
	----------
	dif : str
	    Placeholder for 'difficulty'

	Returns
    -------
    None

    """

    # Largeness of numbers based on difficulty
    x = random.randint(10 ** (2 * difficulties.index(dif)), 10 ** (2 * difficulties.index(dif) + 2) - 1)
    y = random.randint(10 ** (2 * difficulties.index(dif)), 10 ** (2 * difficulties.index(dif) + 2) - 1)

    problem("\nWhat is " + str(x) + " + " + str(y) + " ?\n", x + y, 0)


def subtraction(dif):
    """
    Generates a subtraction problem based on the difficulty and generates 2 random integers,
    then asks the problem by calling the function 'problem()'

    Parameters
	----------
	dif : str
	    Placeholder for 'difficulty'

	Returns
    -------
    None

    """

    # Largeness of numbers based on difficulty
    if dif == difficulties[0]:
        x = int(random.uniform(0, 99))
        y = x + int(random.uniform(0, 99))
    else:
        x = random.randint(10 ** (2 * difficulties.index(dif)), 10 ** (2 * difficulties.index(dif) + 2) - 1)
        y = random.randint(10 ** (2 * difficulties.index(dif)), 10 ** (2 * difficulties.index(dif) + 2) - 1)

    problem("\nWhat is " + str(y) + " - " + str(x) + " ?\n", y - x, 1)


def multiplication(dif):
    """
    Generates a multiplication problem based on the difficulty and generates 2 random integers,
    then asks the problem by calling the function 'problem()'

    Parameters
	----------
	dif : str
	    Placeholder for 'difficulty'

	Returns
    -------
    None

    """

    # Largeness of numbers based on difficulty
    x = random.randint(10 ** (2 * difficulties.index(dif)), 10 ** (2 * difficulties.index(dif) + 1) - 1)
    y = random.randint(10 ** (2 * difficulties.index(dif)), 10 ** (2 * difficulties.index(dif) + 2) - 1)

    problem("\nWhat is " + str(x) + " * " + str(y) + " ?\n", x * y, 2)


def division(dif):
    """
    Generates a division problem based on the difficulty and generates 2 random integers,
    then asks the problem by calling the function 'problem()'

    Parameters
	----------
	dif : str
	    Placeholder for 'difficulty'

	Returns
    -------
    None

    """

    # Largeness of numbers based on difficulty
    x = random.randint(10 ** (difficulties.index(dif)), 10 ** (difficulties.index(dif) + 1) - 1)
    y = x * random.randint(10 ** (difficulties.index(dif)), 10 ** (difficulties.index(dif) + 1) - 1)

    problem("\nWhat is " + str(y) + " / " + str(x) + " ?\n", y / x, 3)


def ask_type(prob):
    """
    Calls the respective problem generator function based on the string 'problem_type'

    Parameters
	----------
	prob : str
	    Placeholder for 'problem_type'

	Returns
    -------
    None

    """

    if prob =='addition':
        addition(difficulty)
    elif prob == 'subtraction':
        subtraction(difficulty)
    elif prob == 'multiplication':
        multiplication(difficulty)
    elif prob == 'divisionq':
        division(difficulty)


def navigate(inp):
    """
    Checks if at any point in time, the user wishes to change the difficulty or the type
    of problem by typing an item from the lists 'difficulties' or 'problem_types'

    Parameters
    ----------
    inp : str
        The previously inputted answer for a problem

    Returns
    -------
    None

    """

    # Difficulty change
    if inp in difficulties:
        global difficulty
        difficulty = inp
        print("\nDifficulty changed to " + inp + ".")
        start()

    # Problem type change
    if inp in problem_types:
        global problem_type
        problem_type = inp
        print("\nProblem type changed to " + inp + ".")
        start()

    # Reset user data
    if inp == 'reset':
        accounts[active].reset()
        print("\n*****************************************")
        print("Account data from user '" + accounts[active].name.rstrip() + "' was reset.")
        print("*****************************************")

        start()

    # Shows the accuracy stats of the user
    if inp == 'stats':
        print("\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
        print("User '" + accounts[active].name.strip() + "' statistics:")

        # Spacing to format the stats so they align
        spaces = ['        ', '     ', '  ', '        ']
        for i in range(0, 4):
            print(problem_types[i].capitalize() + ":" + spaces[i] + accounts[active].answered[i].strip()
                  + " Correctly Answered, " + accounts[active].attempts[i].strip() + " Attempts, ", end='')
            if int(accounts[active].attempts[i]) == 0:
                print("NA% Accuracy")
            else:
                print(str(int(round(int(accounts[active].answered[i])/int(accounts[active].attempts[i])*100, 0)))
                      + "% Accuracy")
        print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
        start()

def start():
    """
    Executes the problems

	Parameters
	----------
	None

    Returns
    -------
    None

    """

    while True:
        ask_type(problem_type)

