# -----------------------------------------------------------------------------
# Name:        Khan Academy (python.py)
# Purpose:     To help students improve on their arithmetic skills
#
#
# Author:      Ethan Wang
# Created:     5-Sep-2018
# Updated:     17-Sep-2018
# -----------------------------------------------------------------------------

import random
import time

# list of different praises
praises = ["Wow! You are a natural!", "Your IQ is above 100!", "Immaculate!", "Egregious!", "Delicious!",
           "Albert Einstein would be jealous!", "You have a big brain!"]

# list of difficulties
difficulties = ['easy', 'medium', 'hard']

# list of problem types
problem_types = ['addition', 'subtraction', 'multiplication']
print("Welcome to Khan Academy!")

# current difficulty level
difficulty = difficulties[0]

# current problem type
problem_type = problem_types[0]


def set_type():
    """
    Sets the type of problem between the 4 arithmetic operators

    Changes the value of the string 'problem_type' to an item in the list 'problem_types'

	Returns
    -------
	str
	returns the input if it is a valid problem type

    """

    setp = input("\nSelect a type of problem: addition, subtraction, multiplication\n")
    while setp not in problem_types:
        print("\nThat is not an option!")
        setp = input("Select a type of problem: addition, subtraction, multiplication\n")
    return setp


def set_dif():
    """
    Sets the difficulty of the problems

    Changes the value of the string 'difficulty' to an item in the list 'difficulties'

	Returns
    -------
	str
	returns the input if it is a valid difficulty

    """

    setd = input("\nSelect a difficulty: easy, medium, hard\n")
    while setd not in difficulties:
        print("\nThat is not an option!")
        setd = input("Select a difficulty: easy, medium, hard\n")
    return setd


def problem(question, correct_answer):
    """
    Asks a problem and checks for the correct answer of the problem

	Parameters
	----------
	question : str
	    The problem that is to be asked based on the type of problem generated by the functions: 'addition()',
	    'subtraction()', 'multiplication()', and 'division()'
	correct_answer : float
	    The correct answer of the problem

    """

    # asks the inputted question
    answer = input(question)

    # begin timer
    start_time = time.time()

    # checks for difficulty or problem type change
    navigate(answer)

    # list of previous answers for question
    answers = [answer]
    while float(answer) != correct_answer:
        # 1 answer
        if len(answers) == 1:
            print("\n" + answers[0] + " is incorrect!")

        # 2 or more answers
        else:
            # lists previous incorrect answers
            print("\n")
            for i in range(len(answers)):
                if i == len(answers) - 1:
                    print("and " + answers[i], end='')
                else:
                    print(answers[i] + ", ", end='')
            print(" are incorrect!")
        print("Try again.")

        # next inputted answer
        answer = input(question)

        # checks for difficulty or problem type change
        navigate(answer)

        # adds answer to list
        answers.append(answer)

    # end timer
    end_time = time.time()

    # random praise upon getting the correct answer
    print(random.choice(praises))

    print("Time: " + str((end_time - start_time)/(10**9)))


def addition(dif):
    """
    Generates an addition problem based on the difficulty and generates 2 random integers,
    then asks the problem by calling the function 'problem()'

    Parameters
	----------
	dif : str
	    Placeholder for 'difficulty'

    """

    # largeness of numbers based on difficulty
    x = random.randint(10 ** (2 * difficulties.index(dif)), 10 ** (2 * difficulties.index(dif) + 2) - 1)
    y = random.randint(10 ** (2 * difficulties.index(dif)), 10 ** (2 * difficulties.index(dif) + 2) - 1)

    problem("\nWhat is " + str(x) + " + " + str(y) + " ?\n", x + y)


def subtraction(dif):
    """
    Generates a subtraction problem based on the difficulty and generates 2 random integers,
    then asks the problem by calling the function 'problem()'

    Parameters
	----------
	dif : str
	    Placeholder for 'difficulty'

    """

    # largeness of numbers based on difficulty
    if dif == difficulties[0]:
        x = int(random.uniform(0, 99))
        y = x + int(random.uniform(0, 99))
    else:
        x = random.randint(10 ** (2 * difficulties.index(dif)), 10 ** (2 * difficulties.index(dif) + 2) - 1)
        y = random.randint(10 ** (2 * difficulties.index(dif)), 10 ** (2 * difficulties.index(dif) + 2) - 1)

    problem("\nWhat is " + str(y) + " - " + str(x) + " ?\n", y - x)


def multiplication(dif):
    """
    Generates a multiplication problem based on the difficulty and generates 2 random integers,
    then asks the problem by calling the function 'problem()'

    Parameters
	----------
	dif : str
	    Placeholder for 'difficulty'

    """

    # largeness of numbers based on difficulty
    x = random.randint(10 ** (2 * difficulties.index(dif)), 10 ** (2 * difficulties.index(dif) + 1) - 1)
    y = random.randint(10 ** (2 * difficulties.index(dif)), 10 ** (2 * difficulties.index(dif) + 2) - 1)

    problem("\nWhat is " + str(x) + " * " + str(y) + " ?\n", x * y)


def ask_type(prob):
    """
    Calls the respective problem generator function based on the string 'problem_type'

    Parameters
	----------
	prob : str
	    Placeholder for 'problem_type'

    """

    if prob == problem_types[0]:
        addition(difficulty)
    elif prob == problem_types[1]:
        subtraction(difficulty)
    elif prob == problem_types[2]:
        multiplication(difficulty)


def navigate(inp):
    """
    Checks if at any point in time, the user wishes to change the difficulty or the type of problem by typing an item
    from the lists 'difficulties' or 'problem_types'

    Parameters
    ----------
    inp : str
        The previously inputted answer for a problem

    """

    # difficulty change
    if inp in difficulties:
        global difficulty
        difficulty = inp
        print("\nDifficulty changed to " + inp + ".")
        start()

    # problem type change
    if inp in problem_types:
        global problem_type
        problem_type = inp
        print("\nProblem type changed to " + inp + ".")
        start()



def start():
    """
    Executes the problems

    """

    while True:
        ask_type(problem_type)


# sets the type of problem
problem_type = set_type()

# sets the difficulty
difficulty = set_dif()

# starts asking problems
start()
